/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import mysqloperation.CarTableModel;

/**
 *
 * @author Administrator
 */
public class TableEditor extends javax.swing.JFrame {

    private MyDBConnection mdbc;
    private java.sql.Statement stmt;

    /**
     * Creates new form MyTable
     */
    public TableEditor() throws Exception {
        mdbc = new MyDBConnection();
        mdbc.init();
        Connection conn = mdbc.getMyConnection();
        stmt = conn.createStatement();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JPanel();
        idFieldlabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameFieldl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        vendorFieldl = new javax.swing.JLabel();
        vendorField = new javax.swing.JTextField();
        tybeCombolabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        commentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataPanel.setPreferredSize(new java.awt.Dimension(400, 99));
        dataPanel.setLayout(new java.awt.GridLayout(4, 2, 2, 1));

        idFieldlabel.setText("ID:");
        dataPanel.add(idFieldlabel);
        dataPanel.add(idField);

        nameFieldl.setText("Name:");
        dataPanel.add(nameFieldl);
        dataPanel.add(nameField);

        vendorFieldl.setText("Vendor:");
        dataPanel.add(vendorFieldl);

        vendorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorFieldActionPerformed(evt);
            }
        });
        dataPanel.add(vendorField);

        tybeCombolabel.setText("Type:");
        dataPanel.add(tybeCombolabel);

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FF", "FR", "MR", "4WD" }));
        typeCombo.setSelectedItem(typeCombo);
        dataPanel.add(typeCombo);

        getContentPane().add(dataPanel, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        commentLabel.setText("Click button to send data.");
        commentLabel.setToolTipText("Click button to send data");
        jPanel2.add(commentLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        ResultSet rs=getResultFromCars();
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carTable.setModel(new CarTableModel(rs));
        mdbc.close(rs);
        jScrollPane1.setViewportView(carTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 418, 645);
    }// </editor-fold>//GEN-END:initComponents

    private void vendorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorFieldActionPerformed
 public String quotate(String content){
    
        return "'"+content+"'";
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String carid=idField.getText();
        String name=nameField.getText();        
        String vendor=vendorField.getText();
        String type=(String)typeCombo.getSelectedItem();
        
        String insertStr="";
        
        try{
            
            insertStr="insert into cars (carid, name, vendor, type) values("
                    +quotate(carid)+","
                    +quotate(name)+","
                    +quotate(vendor)+","
                    +quotate(type)
                    +")";
            
            int done=stmt.executeUpdate(insertStr);
            
            commentLabel.setText("1 row inserted");
           
            getContentPane().removeAll();
            initComponents();
        
        }
        catch(Exception e){
            commentLabel.setText("Error occurred in inserting data");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TableEditor().setVisible(true);
                } catch (Exception e) {

                }
            }
        });
    }

    public ResultSet getResultFromCars() {

        ResultSet rs = null;

        try {
            rs = stmt.executeQuery("Select * from cars");

        } catch (SQLException e) {
        }

        return rs;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carTable;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idFieldlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameFieldl;
    private javax.swing.JLabel tybeCombolabel;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JTextField vendorField;
    private javax.swing.JLabel vendorFieldl;
    // End of variables declaration//GEN-END:variables
}
